// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// removeStretchesFilter
NumericMatrix removeStretchesFilter(NumericMatrix mat, int cutoff);
RcppExport SEXP MACode_removeStretchesFilter(SEXP matSEXP, SEXP cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type cutoff(cutoffSEXP);
    __result = Rcpp::wrap(removeStretchesFilter(mat, cutoff));
    return __result;
END_RCPP
}
