# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Remove consecutive stretches from a matrix of peptide traces.
#'
#' @param mat Trace matrix.
#' @param cutoff Stretch cutoff.
#' @export
removeStretchesFilter <- function(mat, cutoff) {
    .Call('MACode_removeStretchesFilter', PACKAGE = 'MACode', mat, cutoff)
}

